### ISSUE TITLE
Code sample in Index.md is missing parameter

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Email#3]
The 'sendAsHtml' Boolean parameter is missing from the code sample in Index.md

**Comment by gep13** [comment]
@Jericho well spotted, and thanks for fixing.

For something like this, since it isn't documentation that we ship with the actual addin, I am perfectly happy for you to commit this change directly onto the develop branch, unless it is a significant piece of documentation that you would like reviewed.

Similarly, I don't think we need to track the labels on this issue, as I don't think it requires going into the release notes.  Perhaps in your commit message something like:

`(doc) Add the missing parameter in Index.md code sample`

Rather than referencing an issue.
